// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eomyqfyxoikdhtobpdgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvbXlxZnl4b2lrZGh0b2JwZGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1Njg2NzIsImV4cCI6MjA1MzE0NDY3Mn0.eZrgn1Oe-RlhaVQDjR2Lzq-Ze1B0UzH_p_tajc2Ao4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);